#!/bin/bash
#
#

name="John Doe"
email="johndoe31415@foobar.com"
KEYFILE="cms_key.pem"
CERTFILE="cms_cert.pem"

if [ ! -f "$KEYFILE" ]; then
	echo "Generating key..."
	openssl ecparam -genkey -name secp384r1 -out "$KEYFILE"
fi
if [ ! -f "$CERTFILE" ]; then
	echo "Generating certificate..."
	openssl req -x509 -key "$KEYFILE" -days 3650 -nodes \
		-subj "/CN=${name}/emailAddress=${email}" \
		-addext "keyUsage=keyEncipherment,dataEncipherment,digitalSignature" \
		-addext "extendedKeyUsage=emailProtection" \
		-addext "subjectAltName=email:${email}" \
		-addext "1.3.6.1.4.1.61117.1.1349=ASN1:UTF8String:This is just a demo certificate, do not use this ever." \
		-out "$CERTFILE"
fi
